src/Entity/Page.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 */
class Page
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Question", mappedBy="page", cascade={"persist","remove"})
     */
    private $question;


    public function __construct()
    {
        $this->question = new ArrayCollection();
    }
    /**
     * @return Collection|Question[]
     */
    public function getQuestion(): Collection
    {
        return $this->question;
    }


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Quiz",inversedBy="page")
     *
     */
    private $quiz;

    public function getQuiz(): ?Quiz
    {
        return $this->quiz;
    }

    public function setQuiz(?Quiz $quiz): self
    {
        $this->quiz = $quiz;

        return $this;
    }

    /**
     * @ORM\Column(type="integer")
     */
    private $ordre;

    /**
     * @return mixed
     */
    public function getOrdre()
    {
        return $this->ordre;
    }

    /**
     * @param mixed $ordre
     */
    public function setOrdre($ordre): void
    {
        $this->ordre = $ordre;
    }


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre_page;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color_titre_page;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bg_color;

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getTitrePage(): ?string
    {
        return $this->titre_page;
    }

    public function setTitrePage($titre_page)
    {
        $this->titre_page = $titre_page;

        return $this;
    }

    public function getColorTitrePage(): ?string
    {
        return $this->color_titre_page;
    }

    public function setColorTitrePage(?string $color_titre_page)
    {
        $this->color_titre_page = $color_titre_page;

        return $this;
    }

    public function getBgColor(): ?string
    {
        return $this->bg_color;
    }

    public function setBgColor(?string $bg_color)
    {
        $this->bg_color = $bg_color;

        return $this;
    }

    public function __toString()
    {
        return $this->getTitrePage();
    }


}

templates/page/_delete_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Delete page{% endblock %}

{% block body %}
    <h3>Êtes-vous sûr de vouloir supprimer cette page?</h3>
<br>
<br>
<br>
    {{ form_start(form) }}
    <div style="color:red">{{ form_errors(form) }}</div>
    {{ form_widget(form) }}
    <center><button style="background-color:red" class="btn btn-danger">Supprimer</button></center>
    {{ form_end(form) }}



{% endblock %}

templates/page/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/page/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier page{% endblock %}

{% block body %}


    {{ form_start(form) }}
           <div id="page">
            <div>
                {{ form_label(form.titre_page) }}
                {{ form_widget(form.titre_page) }}
            </div>
            <div>
                {{ form_label(form.color_titre_page) }}
                {{ form_widget(form.color_titre_page) }}
            </div>
            <div>
                {{ form_label(form.bg_color) }}
                {{ form_widget(form.bg_color) }}
            </div>


    </div><br>
     <center>
         <button class="btn btn-info">Modifier</button>
     </center>
    {{ form_end(form) }}
    </form>

{% endblock %}

templates/page/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page index{% endblock %}

{% block body %}
    <h1>Page index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre_page</th>
                <th>Color_titre_page</th>
                <th>Bg_color</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for page in pages %}
            <tr>
                <td>{{ page.id }}</td>
                <td>{{ page.titrePage }}</td>
                <td>{{ page.colorTitrePage }}</td>
                <td>{{ page.bgColor }}</td>
                <td>
                    <a href="{{ path('page_show', {'id': page.id}) }}">show</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('page_new') }}">Create new</a>
{% endblock %}

templates/page/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Page{% endblock %}

{% block body %}
    <h1>Create new Page</h1>

    {{ include('page/_form.html.twig') }}

    <a href="{{ path('page_index') }}">back to list</a>
{% endblock %}

templates/page/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page{% endblock %}

{% block body %}
    <h1>Page</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ page.id }}</td>
            </tr>
            <tr>
                <th>Titre_page</th>
                <td>{{ page.titrePage }}</td>
            </tr>
            <tr>
                <th>Color_titre_page</th>
                <td>{{ page.colorTitrePage }}</td>
            </tr>
            <tr>
                <th>Bg_color</th>
                <td>{{ page.bgColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('page_index') }}">back to list</a>


    {{ include('page/_delete_form.html.twig') }}
{% endblock %}