src/Entity/Question.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Parametre;


/**
 * @ORM\Entity(repositoryClass="App\Repository\QuestionRepository")
 */
class Question
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;




    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ReponseParticipant", mappedBy="id_question", cascade={"persist","remove"})
     */
    private $rep;

    /**
     * @return Collection|ReponseParticipant[]
     */
    public function getREp(): Collection
    {
        return $this->rep;
    }



    /**
     * One product has many features. This is the inverse side.
     * @ORM\OneToMany(targetEntity="Reponse", mappedBy="question", cascade={"persist","remove"})
     */
    private $reponse;

    public function __construct() {
        $this->reponse = new ArrayCollection();
        $this->rep = new ArrayCollection();
    }
    /**
     * @return Collection|Reponse[]
     */
    public function getReponse(): Collection
    {
        return $this->reponse;
    }



    /**
     * One Customer has One Cart.
     * @ORM\OneToMany(targetEntity="Parametre", mappedBy="question", cascade={"persist","remove"})
     */
    private $parametre;

    /**
     * @return mixed
     */
    public function getParametre()
    {
        return $this->parametre;
    }

    /**
     * @param mixed $parametre
     */
    public function setParametre($parametre): void
    {
        $this->parametre = $parametre;
    }


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Page",inversedBy="question")
     * @ORM\JoinColumn(nullable=false)
     */
    private $page;

    public function getPage(): ?Page
    {
        return $this->page;
    }

    public function setPage(?Page $page): self
    {
        $this->page = $page;

        return $this;
    }


    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $text_question;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $type_question;

    /**
     * @ORM\Column(type="string", length=2000, nullable=true)
     */
    private $info_bulle;

    /**
     * @ORM\Column(type="string", length=2000, nullable=true)
     */
    private $description_question;


    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $actif;

    /**
     * @return mixed
     */
    public function getActif()
    {
        return $this->actif;
    }

    /**
     * @param mixed $actif
     */
    public function setActif($actif): void
    {
        $this->actif = $actif;
    }



    public function getId(): ?int
    {
        return $this->id;
    }



    public function getTextQuestion(): ?string
    {
        return $this->text_question;
    }

    public function setTextQuestion(string $text_question): self
    {
        $this->text_question = $text_question;

        return $this;
    }

    public function getTypeQuestion(): ?string
    {
        return $this->type_question;
    }

    public function setTypeQuestion(string $type_question): self
    {
        $this->type_question = $type_question;

        return $this;
    }

    public function getInfoBulle(): ?string
    {
        return $this->info_bulle;
    }

    public function setInfoBulle(?string $info_bulle)
    {
        $this->info_bulle = $info_bulle;

        return $this;
    }

    public function getDescriptionQuestion(): ?string
    {
        return $this->description_question;
    }

    public function setDescriptionQuestion(?string $description_question)
    {
        $this->description_question = $description_question;

        return $this;
    }


    public function __toString() {
        return $this->text_question;
    }
}

src/Entity/Reponse.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReponseRepository")
 */
class Reponse
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Question",inversedBy="reponse")
     */
    private $question;

    /**
     * @return mixed
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * @param mixed $question
     */
    public function setQuestion($question): void
    {
        $this->question = $question;
    }


    /**
     * @ORM\Column(type="string", length=2000, nullable=true)
     */
    private $formule;


    /**
     * @ORM\Column(type="string", length=2000, nullable=true)
     */
    private $destext;



    /**
     * @ORM\Column(type="string", length=2000, nullable=true)
     */
    private $desnumber;

    /**
     * @return mixed
     */
    public function getDesnumber()
    {
        return $this->desnumber;
    }

    /**
     * @param mixed $desnumber
     */
    public function setDesnumber($desnumber): void
    {
        $this->desnumber = $desnumber;
    }


    /**
     * @return mixed
     */
    public function getDestext()
    {
        return $this->destext;
    }

    /**
     * @param mixed $destext
     */
    public function setDestext($destext): void
    {
        $this->destext = $destext;
    }


    /**
     * @ORM\Column(type="string", length=2000, nullable=true)
     */
    private $resultatformule;

    /**
     * @return mixed
     */
    public function getFormule()
    {
        return $this->formule;
    }

    /**
     * @param mixed $formule
     */
    public function setFormule($formule): void
    {
        $this->formule = $formule;
    }

    /**
     * @return mixed
     */
    public function getResultatformule()
    {
        return $this->resultatformule;
    }

    /**
     * @param mixed $resultatformule
     */
    public function setResultatformule($resultatformule): void
    {
        $this->resultatformule = $resultatformule;
    }


    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $descriptiondate;

    /**
     * @return mixed
     */
    public function getDescriptiondate()
    {
        return $this->descriptiondate;
    }

    /**
     * @param mixed $descriptiondate
     */
    public function setDescriptiondate($descriptiondate): void
    {
        $this->descriptiondate = $descriptiondate;
    }



    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $descriptionformule;

    /**
     * @return mixed
     */
    public function getDescriptionformule()
    {
        return $this->descriptionformule;
    }

    /**
     * @param mixed $descriptionformule
     */
    public function setDescriptionformule($descriptionformule): void
    {
        $this->descriptionformule = $descriptionformule;
    }

    /**
     * @ORM\Column(type="string", length=2000, nullable=true)
     */
    private $reponse_valide;


    /**
     * @ORM\Column(type="boolean", nullable=true, nullable=true)
     */
    private $etatvf;

    /**
     * @ORM\Column(type="boolean", nullable=true, nullable=true)
     */
    private $etatlist;

    /**
     * @return mixed
     */
    public function getEtatlist()
    {
        return $this->etatlist;
    }

    /**
     * @param mixed $etatlist
     */
    public function setEtatlist($etatlist): void
    {
        $this->etatlist = $etatlist;
    }



    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $etatcaseacocher;

    /**
     * @return mixed
     */
    public function getEtatcaseacocher()
    {
        return $this->etatcaseacocher;
    }

    /**
     * @param mixed $etatcaseacocher
     */
    public function setEtatcaseacocher($etatcaseacocher): void
    {
        $this->etatcaseacocher = $etatcaseacocher;
    }


    /**
     * @return mixed
     */
    public function getEtatvf()
    {
        return $this->etatvf;
    }

    /**
     * @param mixed $etatvf
     */
    public function setEtatvf($etatvf): void
    {
        $this->etatvf = $etatvf;
    }



    public function getId(): ?int
    {
        return $this->id;
    }


    public function getReponseValide(): ?string
    {
        return $this->reponse_valide;
    }

    public function setReponseValide(string $reponse_valide): self
    {
        $this->reponse_valide = $reponse_valide;

        return $this;
    }
}

src/Form/ReponseType.php
<?php

namespace App\Form;

use App\Entity\Reponse;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReponseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('formule',null,[
                'label' => 'Formule :'
            ])
            ->add('destext')
            ->add('desnumber')
            ->add('resultatformule',null,[
                'label' => 'Resultat :'
            ])
            ->add('descriptiondate',null,[
                    'label' => 'Description date :'
            ]
)
            ->add('descriptionformule',null,[
                'label' => 'Description formule :'
            ])
            ->add('reponse_valide', null, [
                'required' =>  true
            ])
            ->add('etatvf')
            ->add('etatlist')
            ->add('etatcaseacocher')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reponse::class,
        ]);
    }
}

src/Controller/ReponseController.php
<?php

namespace App\Controller;

use App\Entity\Reponse;
use App\Form\ReponseType;
use App\Repository\ReponseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reponse")
 */
class ReponseController extends AbstractController
{
    /**
     * @Route("/", name="reponse_index", methods={"GET"})
     */
    public function index(ReponseRepository $reponseRepository): Response
    {
        return $this->render('reponse/index.html.twig', [
            'reponses' => $reponseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="reponse_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reponse = new Reponse();
        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reponse);
            $entityManager->flush();

            return $this->redirectToRoute('reponse_index');
        }

        return $this->render('reponse/new.html.twig', [
            'reponse' => $reponse,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reponse_show", methods={"GET"})
     */
    public function show(Reponse $reponse): Response
    {
        return $this->render('reponse/show.html.twig', [
            'reponse' => $reponse,
        ]);
    }

    /**
     * @Route("/{id}/editReponse", name="reponse_edit", methods={"GET","POST"})
     */
    public function editReponse(Request $request, Reponse $reponse): Response
    {
        $form = $this->createForm(ReponseType::class, $reponse, [
            'action' => $this->generateUrl('reponse_edit', ['id' => $reponse->getId()])
        ]);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $page = $reponse->getQuestion()->getPage()->getId();

            $quiz= $reponse->getQuestion()->getPage()->getQuiz()->getId();


            return $this->redirectToRoute('creerquiz', [
                'id'=>$quiz,
                'page' => $page
            ]);
        }


        return $this->render('reponse/edit.html.twig', [
            'reponse' => $reponse,
            'question' => $reponse->getQuestion(),
            'form' => $form->createView(),
        ]);
    }




    /**
     * @Route("/{id}/editReponse2", name="reponse_edit2", methods={"GET","POST"})
     */
    public function editReponse2(Request $request, Reponse $reponse): Response
    {
        $form = $this->createForm(ReponseType::class, $reponse, [
            'action' => $this->generateUrl('reponse_edit2', ['id' => $reponse->getId()])
        ]);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $page = $reponse->getQuestion()->getPage()->getId();

            $quiz= $reponse->getQuestion()->getPage()->getQuiz()->getId();


            return $this->redirectToRoute('modifier_page', [
                'quiz'=>$quiz,
                'page' => $page
            ]);
        }


        return $this->render('reponse/edit.html.twig', [
            'reponse' => $reponse,
            'question' => $reponse->getQuestion(),
            'form' => $form->createView(),
        ]);
    }





    /**
     * @Route("/{id}", name="reponse_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reponse $reponse): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reponse->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reponse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reponse_index');
    }
}

templates/reponse/_delete_form.html.twig
<form method="post" action="{{ path('reponse_delete', {'id': reponse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reponse.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reponse/_form.html.twig
<style>
    .navbar {
        overflow: hidden;
        background-color: #333;
        position: fixed;
        bottom: 0;
        width: 100%;
    }

    .mb-5 {
        margin-bottom: 5px ! important;
    }
</style>

{{ form_start(form) }}
{% if question.typeQuestion == "Vrai/faux" %}
    {% for p in question.reponse %}
<div  class="row" >
 <div class="col-sm-10" style="background-color:;">
    {{ form_widget(form.reponse_valide, { 'attr':{'class':'form-control'} }) }}
 </div>
    <div class="col-sm-2" style="background-color:;">

    {{ form_widget(form.etatvf, { 'attr':{'class':'form-control'} }) }}
    </div>


    </div>
        {{ form_widget(form.formule, { 'attr':{'hidden':'hidden'} }) }}
    {{ form_widget(form.destext  , { 'attr':{'hidden':'hidden'} }) }}
    {{ form_widget(form.desnumber  , { 'attr':{'hidden':'hidden'} }) }}
    {{ form_widget(form.resultatformule  , { 'attr':{'hidden':'hidden'} }) }}
    {{ form_widget(form.descriptiondate  , { 'attr':{'hidden':'hidden'} }) }}
    {{ form_widget(form.descriptionformule  , { 'attr':{'hidden':'hidden'} }) }}
    {{ form_widget(form.etatlist  , { 'attr':{'hidden':'hidden'} }) }}
    {{ form_widget(form.etatcaseacocher  , { 'attr':{'hidden':'hidden'} }) }}
    {% endfor %}
{% endif %}


                    {% if question.typeQuestion  == "Date" %}
                        {% for p in question.reponse %}

                                {{ form_widget(form.reponse_valide, { 'attr':{'class':'form-control'} }) }}
                                {{ form_widget(form.formule, { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.destext  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.desnumber  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.resultatformule  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.descriptiondate , { 'attr':{'class':'form-control'} }) }}
                                {{ form_widget(form.descriptionformule  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.etatvf  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.etatlist  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.etatcaseacocher  , { 'attr':{'hidden':'hidden'} }) }}
{% endfor %}
                    {% endif %}

                    {% if question.typeQuestion == "Nombre" %}

                        {% for p in question.reponse %}

                                {{ form_widget(form.desnumber , { 'attr':{'class':'form-control'} } ) }}

                                {{ form_widget(form.reponse_valide, { 'attr':{'class':'form-control'} }) }}
                                {{ form_widget(form.formule, { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.destext  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.resultatformule  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.descriptiondate, { 'attr':{'hidden':'hidden'} } ) }}
                                {{ form_widget(form.descriptionformule  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.etatvf  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.etatlist  , { 'attr':{'hidden':'hidden'} }) }}
                                {{ form_widget(form.etatcaseacocher  , { 'attr':{'hidden':'hidden'} }) }}
{% endfor %}
                    {% endif %}



  {% if question.typeQuestion=='Case à cocher' %}

      {% for p in question.reponse %}
          <div class="row">
              <div class="col-sm-10">
                  {{ form_widget(form.desnumber , { 'attr':{'hidden':'hidden'} } ) }}
                  {{ form_widget(form.reponse_valide, { 'attr':{'class':'form-control'} }) }}
                  {{ form_widget(form.formule, { 'attr':{'hidden':'hidden'} }) }}
                  {{ form_widget(form.destext  , { 'attr':{'hidden':'hidden'} }) }}
                  {{ form_widget(form.resultatformule  , { 'attr':{'hidden':'hidden'} }) }}
                  {{ form_widget(form.descriptiondate, { 'attr':{'hidden':'hidden'} } ) }}
                  {{ form_widget(form.descriptionformule  , { 'attr':{'hidden':'hidden'} }) }}
                  {{ form_widget(form.etatvf  , { 'attr':{'hidden':'hidden'} }) }}
                  {{ form_widget(form.etatlist  , { 'attr':{'hidden':'hidden'} }) }}
              </div>
              <div class="col-sm-2">
                  {{ form_widget(form.etatcaseacocher, { 'attr':{'class':'form-control'} }  ) }}
              </div>
          </div>

      {% endfor %}
    {% endif %}

 {% if question.typeQuestion=='Liste déroulante' %}

     {% for p in question.reponse %}
        <div class="row">
            <div class="col-sm-10">
                 {{ form_widget(form.desnumber , { 'attr':{'hidden':'hidden'} } ) }}

                 {{ form_widget(form.reponse_valide, { 'attr':{'class':'form-control'} }) }}
                 {{ form_widget(form.formule, { 'attr':{'hidden':'hidden'} }) }}
                 {{ form_widget(form.destext  , { 'attr':{'hidden':'hidden'} }) }}
                 {{ form_widget(form.resultatformule  , { 'attr':{'hidden':'hidden'} }) }}
                 {{ form_widget(form.descriptiondate, { 'attr':{'hidden':'hidden'} } ) }}
                 {{ form_widget(form.descriptionformule  , { 'attr':{'hidden':'hidden'} }) }}
                 {{ form_widget(form.etatvf  , { 'attr':{'hidden':'hidden'} }) }}
                 {{ form_widget(form.etatcaseacocher , { 'attr':{'hidden':'hidden'} } ) }}
            </div>
            <div class="col-sm-2">
                {{ form_widget(form.etatlist, { 'attr':{'class':'form-control'} } ) }}
            </div>
        </div>
     {% endfor %}
 {% endif %}

 {% if question.typeQuestion=='Calculée' %}

     {% for p in question.reponse %}
         {{ form_widget(form.desnumber , { 'attr':{'hidden':'hidden'} } ) }}

         {{ form_widget(form.reponse_valide, { 'attr':{'hidden':'hidden', 'class' : 'form-control'} }) }}

         {{ form_widget(form.descriptionformule , { 'attr':{'class':'form-control'} }) }}

         {{ form_widget(form.formule, { 'attr':{'class':'form-control'} }) }}

         {{ form_widget(form.resultatformule , { 'attr':{'class':'form-control'} } ) }}

         {{ form_widget(form.destext  , { 'attr':{'hidden':'hidden'} }) }}
         {{ form_widget(form.descriptiondate, { 'attr':{'hidden':'hidden'} } ) }}
         {{ form_widget(form.etatvf  , { 'attr':{'hidden':'hidden'} }) }}
         {{ form_widget(form.etatlist , { 'attr':{'hidden':'hidden'} } ) }}
         {{ form_widget(form.etatcaseacocher , { 'attr':{'hidden':'hidden'} } ) }}
     {% endfor %}
 {% endif %}

<div class="col-sm-4" style="background-color:; padding-left: 91.5%;">
    <br>
    <button style="color: #31b0d5" class="fa fa-pencil"></button>

</div>
{{ form_end(form) }}

templates/reponse/edit.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    {{ include('reponse/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/reponse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reponse index{% endblock %}

{% block body %}
    <h1>Reponse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Formule</th>
                <th>Destext</th>
                <th>Desnumber</th>
                <th>Resultatformule</th>
                <th>Descriptiondate</th>
                <th>Descriptionformule</th>
                <th>Reponse_valide</th>
                <th>Etatvf</th>
                <th>Etatlist</th>
                <th>Etatcaseacocher</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reponse in reponses %}
            <tr>
                <td>{{ reponse.id }}</td>
                <td>{{ reponse.formule }}</td>
                <td>{{ reponse.destext }}</td>
                <td>{{ reponse.desnumber }}</td>
                <td>{{ reponse.resultatformule }}</td>
                <td>{{ reponse.descriptiondate }}</td>
                <td>{{ reponse.descriptionformule }}</td>
                <td>{{ reponse.reponseValide }}</td>
                <td>{{ reponse.etatvf ? 'Yes' : 'No' }}</td>
                <td>{{ reponse.etatlist ? 'Yes' : 'No' }}</td>
                <td>{{ reponse.etatcaseacocher ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('reponse_show', {'id': reponse.id}) }}">show</a>
                    <a href="{{ path('reponse_edit', {'id': reponse.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('reponse_new') }}">Create new</a>
{% endblock %}

templates/reponse/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reponse{% endblock %}

{% block body %}
    <h1>Create new Reponse</h1>

    {{ include('reponse/_form.html.twig') }}

    <a href="{{ path('reponse_index') }}">back to list</a>
{% endblock %}

templates/reponse/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reponse{% endblock %}

{% block body %}
    <h1>Reponse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reponse.id }}</td>
            </tr>
            <tr>
                <th>Formule</th>
                <td>{{ reponse.formule }}</td>
            </tr>
            <tr>
                <th>Destext</th>
                <td>{{ reponse.destext }}</td>
            </tr>
            <tr>
                <th>Desnumber</th>
                <td>{{ reponse.desnumber }}</td>
            </tr>
            <tr>
                <th>Resultatformule</th>
                <td>{{ reponse.resultatformule }}</td>
            </tr>
            <tr>
                <th>Descriptiondate</th>
                <td>{{ reponse.descriptiondate }}</td>
            </tr>
            <tr>
                <th>Descriptionformule</th>
                <td>{{ reponse.descriptionformule }}</td>
            </tr>
            <tr>
                <th>Reponse_valide</th>
                <td>{{ reponse.reponseValide }}</td>
            </tr>
            <tr>
                <th>Etatvf</th>
                <td>{{ reponse.etatvf ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Etatlist</th>
                <td>{{ reponse.etatlist ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Etatcaseacocher</th>
                <td>{{ reponse.etatcaseacocher ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reponse_index') }}">back to list</a>

    <a href="{{ path('reponse_edit', {'id': reponse.id}) }}">edit</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}