src/Entity/Parametre.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ParametreRepository")
 */
class Parametre
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     *
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Question", inversedBy="parametre")
     *
     */
    private $question;

    /**
     * @return mixed
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * @param mixed $question
     */
    public function setQuestion($question): void
    {
        $this->question = $question;
    }


    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $form_text;




    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_caractere;


    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_chiffre;

    /**
     * @return mixed
     */
    public function getNbChiffre()
    {
        return $this->nb_chiffre;
    }

    /**
     * @param mixed $nb_chiffre
     */
    public function setNbChiffre($nb_chiffre): void
    {
        $this->nb_chiffre = $nb_chiffre;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getFormText()
    {
        return $this->form_text;
    }

    /**
     * @param mixed $form_text
     */
    public function setFormText($form_text): void
    {
        $this->form_text = $form_text;
    }

    /**
     * @return mixed
     */
    public function getNbCaractere()
    {
        return $this->nb_caractere;
    }

    /**
     * @param mixed $nb_caractere
     */
    public function setNbCaractere($nb_caractere): void
    {
        $this->nb_caractere = $nb_caractere;
    }




}

src/Form/ParametreType.php
<?php

namespace App\Form;

use App\Entity\Parametre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParametreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('form_text')
            ->add('nb_caractere')
            ->add('nb_chiffre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Parametre::class,
        ]);
    }
}

src/Controller/ParametreController.php
<?php

namespace App\Controller;

use App\Entity\Page;
use App\Entity\Parametre;
use App\Entity\Quiz;
use App\Form\ParametreType;
use App\Repository\ParametreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/parametre")
 */
class ParametreController extends AbstractController
{
    /**
     * @Route("/", name="parametre_index", methods={"GET"})
     */
    public function index(ParametreRepository $parametreRepository): Response
    {
        return $this->render('parametre/index.html.twig', [
            'parametres' => $parametreRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="parametre_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $parametre = new Parametre();
        $form = $this->createForm(ParametreType::class, $parametre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($parametre);
            $entityManager->flush();

            return $this->redirectToRoute('parametre_index');
        }

        return $this->render('parametre/new.html.twig', [
            'parametre' => $parametre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="parametre_show", methods={"GET"})
     */
    public function show(Parametre $parametre): Response
    {
        return $this->render('parametre/show.html.twig', [
            'parametre' => $parametre,
        ]);
    }


    /**
     * @Route("/{id}/editParametre", name="parametre_edit", methods={"GET","POST"})
     */
    public function editparametre(Request $request, Parametre $parametre): Response
    {
        $form = $this->createForm(ParametreType::class, $parametre, [
            'action' => $this->generateUrl('parametre_edit', ['id' => $parametre->getId()])
        ]);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $page = $parametre->getQuestion()->getPage()->getId();

            $quiz= $parametre->getQuestion()->getPage()->getQuiz()->getId();


            return $this->redirectToRoute('creerquiz', [
                'id'=>$quiz,
                'page' => $page
            ]);
        }

        return $this->render('parametre/edit.html.twig', [
            'parametre' => $parametre,
            'question' => $parametre->getQuestion(),
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/{id}/editParametre2", name="parametre_edit2", methods={"GET","POST"})
     */
    public function editparametre2(Request $request, Parametre $parametre): Response
    {
        $form = $this->createForm(ParametreType::class, $parametre, [
            'action' => $this->generateUrl('parametre_edit2', ['id' => $parametre->getId()])
        ]);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $page = $parametre->getQuestion()->getPage()->getId();

            $quiz= $parametre->getQuestion()->getPage()->getQuiz()->getId();


            return $this->redirectToRoute('modifier_page', [
                'quiz'=>$quiz,
                'page' => $page
            ]);
        }

        return $this->render('parametre/edit.html.twig', [
            'parametre' => $parametre,
            'question' => $parametre->getQuestion(),
            'form' => $form->createView(),
        ]);
    }





    /**
     * @Route("/{id}", name="parametre_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Parametre $parametre): Response
    {
        if ($this->isCsrfTokenValid('delete'.$parametre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($parametre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('parametre_index');
    }
}

templates/parametre/_delete_form.html.twig
<form method="post" action="{{ path('parametre_delete', {'id': parametre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ parametre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/parametre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Parametre{% endblock %}

{% block body %}
    <h1>Edit Parametre</h1>
    {{ include('parametre/_form.html.twig', {'button_label': 'Update'}) }}



{% endblock %}

templates/parametre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parametre index{% endblock %}

{% block body %}
    <h1>Parametre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>form_text</th>
                <th>nb_caractere</th>
                <th>nb_chiffre</th>

                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for parametre in parametres %}
            <tr>
                <td>{{ parametre.id }}</td>
                <td>{{ parametre.formText }}</td>
                <td>{{ parametre.nbCaractere }}</td>
                <td>{{ parametre.nbChiffre }}</td>

                <td>
                    <a href="{{ path('parametre_show', {'id': parametre.id}) }}">show</a>
                    <a href="{{ path('parametre_edit', {'id': parametre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('parametre_new') }}">Create new</a>
{% endblock %}

templates/parametre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Parametre{% endblock %}

{% block body %}
    <h1>Create new Parametre</h1>

    {{ include('parametre/_form.html.twig') }}

    <a href="{{ path('parametre_index') }}">back to list</a>
{% endblock %}

templates/parametre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parametre{% endblock %}

{% block body %}
    <h1>Parametre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ parametre.id }}</td>
            </tr>
            <tr>
                <th>form_text</th>
                <td>{{ parametre.formText }}</td>
            </tr>
            <tr>
                <th>nb_caractere</th>
                <td>{{ parametre.nbCaractere }}</td>
            </tr>
            <tr>
                <th>nb_chiffre</th>
                <td>{{ parametre.nbChiffre }}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('parametre_index') }}">back to list</a>

    <a href="{{ path('parametre_edit', {'id': parametre.id}) }}">edit</a>

    {{ include('parametre/_delete_form.html.twig') }}
{% endblock %}