src/Entity/Quiz.php
<?php
namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Entity\User;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

use Symfony\Component\HttpFoundation\File\File;
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Quiz
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Page", mappedBy="quiz", cascade={"persist","remove"})
     * @ORM\OrderBy({"ordre" = "ASC"})
     */
    private $page;

    public function __construct()
    {
        $this->page = new ArrayCollection();
        $this->user = new ArrayCollection();
        $this->terminer = false;
    }
    /**
     * @return Collection|Page[]
     */
    public function getPage(): Collection
    {
        return $this->page;
    }



    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ParticipantQuiz", mappedBy="quiz", cascade={"persist","remove"})
     */
    private $participantquiz;


    /**
     * @return mixed
     */
    public function getParticipantquiz()
    {
        return $this->participantquiz;
    }

    /**
     * @param mixed $participantquiz
     */
    public function setParticipantquiz($participantquiz): void
    {
        $this->participantquiz = $participantquiz;
    }


    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $datecreerquiz = null;

    /**
     * @return mixed
     */
    public function getDatecreerquiz()
    {
        return $this->datecreerquiz;
    }

    /**
     * @param mixed $datecreerquiz
     */
    public function setDatecreerquiz($datecreerquiz): void
    {
        $this->datecreerquiz = $datecreerquiz;
    }


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User",inversedBy="quiz")
     *
     */
    private $user;

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void
    {
        $this->user = $user;
    }



    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $terminer;

    /**
     * @return mixed
     */
    public function getTerminer()
    {
        return $this->terminer;
    }

    /**
     * @param mixed $terminer
     */
    public function setTerminer($terminer): void
    {
        $this->terminer = $terminer;
    }


    /**
     * @ORM\Column(type="string")
     *
     */
    private $brochure;

    public function getBrochure()
    {
        return $this->brochure;
    }

    public function setBrochure($brochure)
    {
        $this->brochure = $brochure;

        return $this;
    }

    /**
     * @ORM\Column(type="string")
     *
     *
     */
private $categorie;

    /**
     * @return mixed
     */
    public function getCategorie()
    {
        return $this->categorie;
    }

    /**
     * @param mixed $categorie
     */
    public function setCategorie($categorie): void
    {
        $this->categorie = $categorie;
    }


    /**
     * @ORM\Column(type="string", length=300)
     */
    private $titre;
    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $color_titre;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $police;
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $gras;
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $italique;




    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $description;
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $mode_correction;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $temps_dispo;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_question;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_page;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_tentative;
    /**
     * @return mixed
     */
    public function getNbTentative()
    {
        return $this->nb_tentative;
    }
    /**
     * @param mixed $nb_tentative
     */
    public function setNbTentative($nb_tentative): void
    {
        $this->nb_tentative = $nb_tentative;
    }
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $melange_question;
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $ouvrire_quiz = null;
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fermer_quiz = null;
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $send_mail;
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $imprime_pdf;
    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $entete;
    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $pied;
    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $message_s;
    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $message_e;




    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $timequiz;

    /**
     * @return mixed
     */
    public function getTimequiz()
    {
        return $this->timequiz;
    }

    /**
     * @param mixed $timequiz
     */
    public function setTimequiz($timequiz): void
    {
        $this->timequiz = $timequiz;
    }


    public function getId(): ?int
    {
        return $this->id;
    }
    public function getTitre(): ?string
    {
        return $this->titre;
    }
    public function setTitre(string $titre): self
    {
        $this->titre = $titre;
        return $this;
    }
    public function getColorTitre(): ?string
    {
        return $this->color_titre;
    }
    public function setColorTitre(?string $color_titre): self
    {
        $this->color_titre = $color_titre;
        return $this;
    }
    public function getPolice(): ?string
    {
        return $this->police;
    }
    public function setPolice(?string $police): self
    {
        $this->police = $police;
        return $this;
    }
    public function getGras(): ?bool
    {
        return $this->gras;
    }
    public function setGras(?bool $gras): self
    {
        $this->gras = $gras;
        return $this;
    }
    public function getItalique(): ?bool
    {
        return $this->italique;
    }
    public function setItalique(?bool $italique): self
    {
        $this->italique = $italique;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }
    public function setDescription(string $description): self
    {
        $this->description = $description;
        return $this;
    }
    public function getModeCorrection(): ?bool
    {
        return $this->mode_correction;
    }
    public function setModeCorrection(bool $mode_correction): self
    {
        $this->mode_correction = $mode_correction;
        return $this;
    }

    public function getTempsDispo()
    {
        return $this->temps_dispo;
    }
    public function setTempsDispo( $temps_dispo): self
    {
        $this->temps_dispo = $temps_dispo;
        return $this;
    }
    public function getNbQuestion(): ?int
    {
        return $this->nb_question;
    }
    public function setNbQuestion(int $nb_question): self
    {
        $this->nb_question = $nb_question;
        return $this;
    }
    public function getNbPage(): ?int
    {
        return $this->nb_page;
    }
    public function setNbPage(int $nb_page): self
    {
        $this->nb_page = $nb_page;
        return $this;
    }
    public function getMelangeQuestion(): ?bool
    {
        return $this->melange_question;
    }
    public function setMelangeQuestion(?bool $melange_question): self
    {
        $this->melange_question = $melange_question;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getOuvrireQuiz()
    {
        return $this->ouvrire_quiz;
    }

    /**
     * @param mixed $ouvrire_quiz
     */
    public function setOuvrireQuiz($ouvrire_quiz): void
    {
        $this->ouvrire_quiz = $ouvrire_quiz;
    }

    /**
     * @return mixed
     */
    public function getFermerQuiz()
    {
        return $this->fermer_quiz;
    }

    /**
     * @param mixed $fermer_quiz
     */
    public function setFermerQuiz($fermer_quiz): void
    {
        $this->fermer_quiz = $fermer_quiz;
    }


    public function getSendMail(): ?bool
    {
        return $this->send_mail;
    }
    public function setSendMail(?bool $send_mail): self
    {
        $this->send_mail = $send_mail;
        return $this;
    }
    public function getImprimePdf(): ?bool
    {
        return $this->imprime_pdf;
    }
    public function setImprimePdf(?bool $imprime_pdf): self
    {
        $this->imprime_pdf = $imprime_pdf;
        return $this;
    }
    public function getEntete(): ?string
    {
        return $this->entete;
    }
    public function setEntete(?string $entete): self
    {
        $this->entete = $entete;
        return $this;
    }
    public function getPied(): ?string
    {
        return $this->pied;
    }
    public function setPied(string $pied): self
    {
        $this->pied = $pied;
        return $this;
    }
    public function getMessageS(): ?string
    {
        return $this->message_s;
    }
    public function setMessageS(string $message_s): self
    {
        $this->message_s = $message_s;
        return $this;
    }
    public function getMessageE(): ?string
    {
        return $this->message_e;
    }
    public function setMessageE(string $message_e): self
    {
        $this->message_e = $message_e;

templates/base.html.twig
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}

    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}

        <nav class="navbar navbar-expand-lg navbar-dark navbar-bg {{ app.session.flashbag.peek('success')|length > 0 ? '' : 'mb-5' }}">

        {% for message in app.flashes('success') %}

            <div class="alert alert-success">

                {{ message }}
                </div>


        {% endfor %}
        </nav>

        <nav class="navbar navbar-expand-lg navbar-dark navbar-bg {{ app.session.flashbag.peek('danger')|length > 0 ? '' : 'mb-5' }}">

            {% for message in app.flashes('danger') %}
                <div class="alert alert-danger">
                    {{ message }}
                </div>
            {% endfor %}
        </nav>

        <script>
            $(".alert").delay(5000).fadeOut(5000);
        </script>
    </body>
</html>

templates/dashboard.html.twig
{% extends '/bundles/EasyAdminBundle/default/layout.html.twig' %}

{% set _content_title = 'ESPACE ADMINISTRATEUR' %}

{% block page_title -%}
    {{ _content_title }}

{%- endblock %}

{% block content_header %}

   <div class="row">
       <div class="col-sm-8">
           <div class="form-group row">
               <h1 class="title">{{ _content_title }}</h1>
           </div>
       </div>

       <div class="col-sm-4">
<br>
                <!--   <input id="myInput" class="form-control" type="text" placeholder="Recherche..">-->
           </div>
   </div>



{% endblock %}
{% block main %}
    <style>

    </style>
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <style>

            body {
                font-family: Arial, Helvetica, sans-serif;
            }

            .flip-card {
                background-color: transparent;
                width: 300px;
                height: 300px;
                perspective: 1000px;
            }

            .flip-card-inner {
                position: relative;
                width: 100%;
                height: 100%;
                text-align: center;
                transition: transform 0.6s;
                transform-style: preserve-3d;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            }

            .flip-card:hover .flip-card-inner {
                transform: rotateY(180deg);
            }

            .flip-card-front, .flip-card-back {
                position: absolute;
                width: 100%;
                height: 100%;
                backface-visibility: hidden;
            }

            .flip-card-front {
                background-color: white;
                color: black;
                z-index: 2;
            }

            .flip-card-back {
                background-color: #2980b9;
                color: white;
                transform: rotateY(180deg);
                z-index: 1;
            }
            .font-family: Verdana,sans-serif;

        </style>
    </head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="noindex, nofollow, noarchive, nosnippet, noodp, noimageindex, notranslate, nocache" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="generator" content="EasyAdmin" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  >

    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myDIV *").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

    {% set nb = 0 %}
    {% set nbquiz=1 %}
    {% set usernb=0 %}
    {% set total=0 %}
    {% set idquiz = 0 %}
            <br>

        <br>
    <center>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">



            {% if quiz|length != 0 %}
                <div class="row" id="myDIV"><br><br>

                {% for p in quiz %}
                    <div class="modal fade" id="show-{{ p.id }}" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header" style="background-color:	#87CEEB">
                                    <h2 class="modal-title text-white">Détail quiz</h2>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body" style="text-align: left;     font-family: Verdana,sans-serif;">
                                    <b>Titre : </b> <font color="{{p.colorTitre}}">{{ p }}</font><br><br>
                                    <b>Déscription : </b>{{ p.description }}<br><br>
                                    <b> Nombre des tentatives : </b>
                                    {% if p.nbTentative ==1000 %}
                                        Illimité
                                    {% else %}
                                        {{ p.nbTentative }}
                                    {% endif %}
                                    <br><br>
                                    <b>Date céartion :</b> {{ p.datecreerquiz ? p.datecreerquiz|date('Y-m-d') : '' }}<br><br>

                                    <b>Date ouverture de quiz : </b>
                                    {% if p.ouvrireQuiz == null %}
                                        Illimité
                                    {% else %}
                                        {{ p.ouvrireQuiz ? p.ouvrireQuiz|date('Y-m-d') : '' }}
                                    {% endif %}
                                    <br><br>
                                    <b>Date fermeture de quiz : </b>
                                    {% if p.fermerQuiz == null %}
                                        Illimité
                                    {% else %}
                                        {{ p.fermerQuiz ? p.fermerQuiz|date('Y-m-d') : '' }}<br><br>
                                    {% endif %}

                                    {% if p.brochure == "null" %}
                                      <center>  <img width="180" height="180" src="{{ asset('logoquiz/logonull.jpg' ) }}"></center>
                                    {% else %}
                                        <center>
                                            <img src="{{ asset('uploads/brochures/' ~ p.brochure) }}" alt="Avatar" style="width:180px;height:180px;">
                                        </center>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                    </div>


                    {% if p.user == user %}
                        {% set nb = nb+1 %}
                        <div class="col-sm-3"  >
                            <div class="flip-card" style="background-color:;" >

                                <div class="flip-card-inner">

                                    <div class="flip-card-front">
                                        {% if p.brochure == "null" %}
                                            <br>
                                            <div class="container"  >

                                                <div style="height: px; background-color: #ADD8E6; ">
                                                    <div class="card-body" style="height: 59px; ">
                                                        <p class="titrequiz">{% if p.titre|length > 21 %}{{ p.titre|slice(0, 20) ~ '...' }}{% else %}{{ p.titre }}{% endif %}</p>
                                                    </div>
                                                </div><br>
                                                <img width="180" height="180" src="{{ asset('logoquiz/logonull.jpg' ) }}">

                                            </div>
                                        {% else %}
                                                <br>
                                            <div class="container" >
                                                <div style="height: px;background-color: #ADD8E6; ">
                                                    <div class="card-body" style="height: 60px; ">
                                                        <p class="titrequiz">{% if p.titre|length > 21 %}{{ p.titre|slice(0, 20) ~ '...' }}{% else %}{{ p.titre }}{% endif %}</p>
                                                    </div>
                                                </div><br>
                                                <img src="{{ asset('uploads/brochures/' ~ p.brochure) }}" alt="Avatar" style="width:180px;height:180px;">
                                            </div>
                                        {% endif %}
                                    </div>
                                        <div class="flip-card-back">
                                            <br><br>
                                            <p class="titrequiz">{% if p.titre|length > 21 %}{{ p.titre|slice(0, 20) ~ '...' }}{% else %}{{ p.titre }}{% endif %}</p>

                                                {% for h in participant %}

                                                    {% if p.id == h.idQuiz %}
                                                        <b>{{ h.NbParticipant }} participants</b>

                                                    {% endif %}

                                                {% endfor %}

                                            <p> {% if p.description|length > 21 %}{{ p.description|slice(0, 200) ~ '...' }}{% else %}{{ p.description }}{% endif %}</p>
                                            <div>
                                                <a href="#" class="btn btn-success"  data-target="#show-{{ p.id }}" data-toggle="modal"   >Voir</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <br>
                        </div>

                    {% endif %}
                {% endfor %}

                </div>

            {% endif %}
    </center>

    {% for quiz in quiz %}

        {% if quiz.user == user %}
        {% set nb = nb+1 %}
        {% endif %}
    {% endfor %}
    {% if nb == 0 %}
        <center><h1>Aucun résultat trouvé</h1></center><br>
    {% endif %}

{% endblock %}

templates/index.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Quiz online</title>
    <link href="{{ asset('template/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('template/css/main.css') }}" rel="stylesheet">
    <link href="{{ asset('template/css/font-awesome.min.css') }}" rel="stylesheet">


    <!--[if lt IE 9]>
    <script src="{{ asset('template/js/html5shiv.js') }}"></script>
    <script src="{{ asset('template/js/respond.min.js') }}"></script>
    <![endif]-->

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="{{ asset('template/images/quiz.ico') }}">
</head><!--/head-->

<body>

<!--.preloader-->
<div class="preloader"> <i class="fa fa-circle-o-notch fa-spin"></i></div>
<!--/.preloader-->

<header id="home">
    <div id="home-slider" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active" style="background-image: url({{ asset('template/images/slider/1.jpg') }})">
                <div class="caption">
                    <h1 class="animated fadeInLeftBig">Bienvenue chez <span>Quiz</span></h1>

                    <a data-scroll class="btn btn-start animated fadeInUpBig" href="{{ path('index') }}">Prêt à participer ?</a>
                </div>
            </div>
            <div class="item" style="background-image: url({{ asset('template/images/slider/2.jpg') }})">
                <div class="caption">
                    <h1 class="animated fadeInLeftBig">Créer votre propre <span>Quiz</span></h1>

                    <a data-scroll class="btn btn-start animated fadeInUpBig" href="{{ path('fos_user_security_login') }}">Prêt à démarrer ?</a>
                </div>
            </div>

        </div>
        <a class="left-control" href="#home-slider" data-slide="prev"><i class="fa fa-angle-left"></i></a>
        <a class="right-control" href="#home-slider" data-slide="next"><i class="fa fa-angle-right"></i></a>



    </div><!--/#home-slider-->

</header>
<script type="text/javascript" src="{{ asset('template/js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ asset('template/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template/js/jquery.inview.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template/js/wow.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template/js/mousescroll.js') }}"></script>
<script type="text/javascript" src="{{ asset('template/js/smoothscroll.js') }}"></script>
<script type="text/javascript" src="{{ asset('template/js/jquery.countTo.js') }}"></script>
<script type="text/javascript" src="{{ asset('template/js/lightbox.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template/js/main.js') }}"></script>

</body>
</html>

templates/vich_uploader_image.html.twig
<a href="#" class="easyadmin-thumbnail" data-featherlight="#easyadmin-lightbox-{{ item.id }}" data-featherlight-close-on-click="anywhere">
    {# the second parameter is the name of the property with the UploadableField annotation #}
    <img src="{{ vich_uploader_asset(item, 'imageFile') }}">
</a>

<div id="easyadmin-lightbox-{{ item.id }}" class="easyadmin-lightbox">
    {# the second parameter is the name of the property with the UploadableField annotation #}
    <img src="{{ vich_uploader_asset(item, 'imageFile') }}">
</div>